import type { Metadata } from "next";
import { Sora } from "next/font/google";
import { SmoothScroller } from "@/components/ui/smooth-scroller";
import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Personal Trainer Lead System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sora.variable}>
      <body
        className={`${sora.className} bg-transparent overflow-x-hidden antialiased`}
      >
        <SmoothScroller />

        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
